version: '3'

services:

  proxy:
    image: ghcr.io/markusgnigler/n4d:latest
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    environment:
      HOST_IP: 127.0.0.1
    volumes:
      - ./www:/var/www
      # - ./conf.d:/etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d