name: publish dr4n image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  push-dr4n:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN  }}

    - name: switch docker driver
      run: |
        docker buildx create --use

    - name: push image
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64,linux/arm/v7 \
          --tag ghcr.io/markusgnigler/n4d:latest \
          --tag ghcr.io/markusgnigler/n4d:$(cat VERSION | awk -F '.' '{ print $1 }' | tr ' ' '.') \
          --tag ghcr.io/markusgnigler/n4d:$(cat VERSION | awk -F '.' '{ print $1,$2 }' | tr ' ' '.') \
          --tag ghcr.io/markusgnigler/n4d:$(cat VERSION | awk -F '.' '{ print $1,$2,$3 }' | tr ' ' '.') \
          --push \
          .

          
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3
      
    # - name: Build and push
    #   uses: docker/build-push-action@v5
    #   with:
    #       push: true
    #       secrets: |
    #         GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}
    #       tags: |
    #           ghcr.io/markusgnigler/n4d:latest
    #           ghcr.io/markusgnigler/n4d:$(cat VERSION | awk -F '.' '{ print $1 }' | tr ' ' '.')
    #           ghcr.io/markusgnigler/n4d:$(cat VERSION | awk -F '.' '{ print $1,$2 }' | tr ' ' '.')
    #           ghcr.io/markusgnigler/n4d:$(cat VERSION | awk -F '.' '{ print $1,$2,$3 }' | tr ' ' '.')
          
